apiVersion: apps/v1
kind: Deployment
metadata:
  name: xango-web-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xango-web
  template:
    metadata:
      labels:
        app: xango-web
    spec:
      containers:
      - name: xango-web
        image: xango-web:latest
        ports:
        - containerPort: 7167
---
apiVersion: v1
kind: Service
metadata:
  name: xango-services-authapi-service
spec:
  selector:
    app: xango-web
  ports:
  - port: 80
    targetPort: 7167
  type: LoadBalancer
