apiVersion: apps/v1
kind: Deployment
metadata:
  name: coupon-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coupon-api
  template:
    metadata:
      labels:
        app: coupon-api
    spec:
      containers:
        - name: coupon-api
          image: coupon-api:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 7001
---
apiVersion: v1
kind: Service
metadata:
  name: coupon-api
spec:
  selector:
    app: coupon-api
  ports:
    - port: 443
      targetPort: 7001
  type: ClusterIP
