apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-api
  template:
    metadata:
      labels:
        app: inventory-api
    spec:
      containers:
        - name: inventory-api
          image: xangoservicesinventoryapi:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 7010
---
apiVersion: v1
kind: Service
metadata:
  name: xangoservicesinventoryapi
spec:
  selector:
    app: inventory-api
  ports:
    - port: 7010
      targetPort: 7010
  type: ClusterIP
