apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-api
  template:
    metadata:
      labels:
        app: order-api
    spec:
      containers:
        - name: order-api
          image: xangoservicesorderapi:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 7004
---
apiVersion: v1
kind: Service
metadata:
  name: xangoservicesorderapi
spec:
  selector:
    app: order-api
  ports:
    - port: 7004
      targetPort: 7004
  type: ClusterIP
